Implemented `stage_file` and `unstage_file`
lewis6991/gitsigns.nvim pull request #128
Opened 2021-04-05 11:11 UTC by tomaskallup

This allow users to run `lua require"gitsigns".stage_file()` to stage
all changes in a file and `lua require"gitsigns".unstage_file()` to
unstage all changes in a file.

Closes: #127

Also a sidenote, it would be nice to have some sort of "developing" section in readme. Setting up teal isn't the worst, but having the requirements in there would be helpful.

2021-04-05 11:15 UTC, tomaskallup commented
Would love feedback, it seems to work great for me, there are messages if there's nothing to stage and the signs seem to update instantly.

Also, should I look into making tests for this?

2021-04-05 12:53 UTC, lewis6991 requested changes
If you can, a testcase for this would be great.

2021-04-05 12:53 UTC, lewis6991 commented on teal/gitsigns/git.tl
> +    args = {'add', file},
One of the design principles of gitsigns is that it only operates with the buffer contents and not the saved file in the work tree.

So we would need to pass the list of buffer lines to this function and run the appropriate command the stages those lines. There are probably a few ways to do this. One way would be to create a patch and pipe that in to stdin just like how we stage individual hunks.

2021-04-05 12:53 UTC, lewis6991 commented on teal/gitsigns/config.tl
> +      ['n <leader>fu'] = '<cmd>lua require"gitsigns".unstage_file()<CR>',
I've restricted all the automatically applied mappings with the `<leader>h` prefix.

You could use `<leader>hS` and `<leader>hU` for the default mappings.

2021-04-05 12:53 UTC, lewis6991 commented on teal/gitsigns.tl
> +  -- We cannot update the status bar as that requires a full diff.
This comment needs updating. Since we are essentially removing all the signs we can simply clear the status bar variable.

2021-04-05 12:53 UTC, lewis6991 commented on teal/gitsigns.tl
> +  local hunk_signs = process_hunks(hunks)
As I've explained in another comment, we should only work with buffer contents.

Here there is an issue where if there are unsaved changes in the buffer, the hunks won't allign with that hunks that `git add <file>` will stage which will result in erroneous/missing signs.

If we know we are simply applying all the hunks in the buffer we should just be able to remove all the signs.

2021-04-05 12:53 UTC, lewis6991 commented on teal/gitsigns.tl
> +  await(git.unstage_file(bcache.toplevel, bcache.file))
Unlike `git add`, `git reset` doesn't operate on the worktree so passing the filename here is ok.

FYI, note that `bcache.staged_diffs` currently only contains hunks that were staged by `stage_hunk` in the same neovim session. If you stage some hunks outside of neovim or restart neovim then it won't contain all the staged hunks. We can fix this by initially populating staged_hunks with a `git-diff` between the `HEAD` and the index.

The reason I mention this is that the signs we add in line 357 won't be complete, but this is ok since rest of the signs will be updated by an index update.

It is definitely adding a detailed comment here to make this clear.

2021-04-05 12:53 UTC, lewis6991 commented on teal/gitsigns.tl
> +  if #hunks == 0 then
We shouldn't do this unless we guarantee that `bcache.staged_diffs` is complete (which it isn't), see comment below.

2021-04-05 12:53 UTC, lewis6991 commented on teal/gitsigns.tl
> +local stage_file = void_async(function()
Make sure you document this function and `unstage_file` in `doc/gitsigns.txt`

2021-04-05 12:53 UTC, lewis6991 commented on teal/gitsigns/git.tl
> +M.stage_file = a.wrap(function(
I'd probably rename this to `stage_buffer`.

2021-04-05 16:01 UTC, tomaskallup commented on teal/gitsigns/git.tl
> +    args = {'add', file},
I currently have a solution which modifies `create_patch` to accept an array of hunks and return the diff for multiple hunks. That way this functions is not needed and I just pass the result of `create_patch` with all modified hunks to `stage_lines`.

Is that an acceptable solution?

2021-04-05 16:01 UTC, tomaskallup commented on teal/gitsigns/config.tl
> +      ['n <leader>fu'] = '<cmd>lua require"gitsigns".unstage_file()<CR>',
Ah I see, I have these modified a bit (since my `<leader>h` is already occupied), I'll change this.

2021-04-05 16:03 UTC, lewis6991 commented on teal/gitsigns/git.tl
> +    args = {'add', file},
Yeah that's more of what I had in mind.

2021-04-05 16:11 UTC, tomaskallup commented on teal/gitsigns.tl
> +  if #hunks == 0 then
I'll try to add proper comments and probably create an issue, to implement the `bcache.staged_diffs` population, so that this can be improved.

2021-04-05 16:57 UTC, lewis6991 requested changes
Looking good! Just a few more things.

Also looks like you've accidently broken indentation in a few places.

2021-04-05 16:57 UTC, lewis6991 commented on teal/gitsigns.tl
> +  uv.fs_realpath(api.nvim_buf_get_name(bufnr))
You've broken some indentation here. I assume this was accidental.

2021-04-05 16:57 UTC, lewis6991 commented on teal/gitsigns/git.tl
> +        error('Cannot add file. Command stderr:\n\n'..s)
Update

2021-04-05 16:57 UTC, lewis6991 commented on teal/gitsigns/signs.tl
> +end
You don't need this, you can just call `remove` with one argument:

```lua
signs.remove(bufnr)
```

In lua/teal all variable/arguments are nullable so it's an accepted idiom to use nils like this. It's quirky but you get used to it.

2021-04-05 16:57 UTC, lewis6991 commented on teal/gitsigns.tl
> +  Status:clear()
This will clear all the buffer variables including `b:gitsigns_head` which is undesirable. When I said clear the status I meant set `status.{added,removed,changed} = {0,0,0}` (sorry for not being clear). `status.tl` doesn't really have a nice way of doing this so you might need to tweak things a bit.

2021-04-05 16:57 UTC, lewis6991 commented on teal/gitsigns.tl
> +  end
Can you put this into a function so the code isn't duplicated? Something like:

```lua
local add_to_index = void_async(function(bcache: CacheElem)
  ...
end)
```

Not the best name so choose something else if you can think of something better. Maybe `ensure_file_in_index`?

2021-04-05 16:57 UTC, lewis6991 commented on doc/gitsigns.txt
> +                Unstage all hunks in current buffer. Note: Unlike
This isn't really a buffer operation. Note we also have `reset_buffer` which alters the buffer contents to match the index, this function alters the index to match HEAD. Maybe we can keep the name for now but the description should be something like:
> Undo all staged hunks for the current buffers file in the index. ...

Maybe `reset_index` is a better name? What do you think?

2021-04-05 16:59 UTC, lewis6991 commented
> Also a sidenote, it would be nice to have some sort of "developing" section in readme. Setting up teal isn't the worst, but having the requirements in there would be helpful.

Yeah, this would be good to add. Would appreciate your feedback as a new contributer on what you think is worth including.

2021-04-05 17:10 UTC, tomaskallup commented on teal/gitsigns.tl
> +  uv.fs_realpath(api.nvim_buf_get_name(bufnr))
Ah my bad, I have diffuculties getting `teal` setup properly, as the treesitter grammar causes crashes for me and I can't get the language server running, so I'm relying on vim-teal.

2021-04-05 17:13 UTC, tomaskallup commented on doc/gitsigns.txt
> +                Unstage all hunks in current buffer. Note: Unlike
Maybe something like `reset_buffer_index` or `reset_buffer_in_index`? It would be nice to indicate that the index is modified only for the current buffer.

2021-04-05 17:13 UTC, lewis6991 commented on teal/gitsigns.tl
> +  uv.fs_realpath(api.nvim_buf_get_name(bufnr))
If it helps I use https://github.com/iamcco/diagnostic-languageserver with this config:

```lua
setup(nvim_lsp.diagnosticls, {
  filetypes = {'teal'},
  init_options = {
    filetypes = {
      teal   = {'tealcheck'}
    },
    linters = {
      tealcheck = {
        sourceName = "tealcheck",
        command = "tl",
        args = {'check', '%file'},
        isStdout = false,
        isStderr = true,
        rootPatterns = {"tlconfig.lua", ".git"},
        formatPattern = {
          '^([^:]+):(\\d+):(\\d+): (.+)$',
          {
            sourceName = 1,
            sourceNameFilter = true,
            line = 2,
            column = 3,
            message = 4
          }
        }
      }
    }
  }
})

```

2021-04-05 17:15 UTC, lewis6991 commented on doc/gitsigns.txt
> +                Unstage all hunks in current buffer. Note: Unlike
`reset_buffer_index` seems ok.

2021-04-05 17:26 UTC, tomaskallup commented
> > Also a sidenote, it would be nice to have some sort of "developing" section in readme. Setting up teal isn't the worst, but having the requirements in there would be helpful.
> 
> Yeah, this would be good to add. Would appreciate your feedback as a new contributer on what you think is worth including.

Definitely info about the setup (sources are in `teal` - which needs to be installed, compiled using `make`, tests are written in plenary [not sure if it's actualy plenary running the tests] and they can be run using `make test`). And if you have working nvim setup, a piece of config with the required stuff (what to use for highlighting and what to use for error checking) would be great.

I'll try to finish up this PR tomorrow, I'm having a bit of a struggle with the test, so I'll let u know if I need some help. The other stuff should be pretty easy to fix.

2021-04-06 07:18 UTC, tomaskallup commented on teal/gitsigns.tl
> +  end
With `void_async` it gave me an error when using `await` on it when compiling: `argument 1: got <any type>, expected future0`
The definition is same as you suggested, calling it looks like this:
```lua
  await(ensure_file_in_index(bcache))
```

2021-04-06 08:10 UTC, lewis6991 commented on teal/gitsigns.tl
> +  end
You can only `await`on an `async` function but not a `void_async` which be called directly like lua regular function.

Just change `void_async` -> `async`

2021-04-06 08:15 UTC, tomaskallup commented on teal/gitsigns.tl
> +  end
Yep, I just did. Pushed the fixes, managed to get everything working.

2021-04-06 08:16 UTC, tomaskallup commented
Also about commit history, should I squash them into one (once you approve), so you don't endup with the review fixes in repo?

2021-04-06 08:28 UTC, lewis6991 commented
Yes please squash them.

2021-04-06 09:02 UTC, tomaskallup commented
I've rebased the commits into one. Hope the commit message is complete enough

2021-04-06 09:03 UTC, weilbith commented
One minor question from my side. I saw this PR in my notifications as I'm watching the project. And I must admit that I'm wondering where the borders of this plugin are intended to end. I'm a big fan of minimal plugins which do one thing and do it good. The plugin is called `gitsigns`. I think it makes sense and is nice that is also provide little extensions to interact with the hunks it highlights.  For example do I consider the hunk reset quite helpful as it helps me while writing code. But interacting with a whole file sounds not like this is related anymore to signs or their according hunks. This goes more into the direction of what other git related plugins focus on. So I start to wonder what is in the scope/target of this plugin here. Which features will be accepted and which will get declined? 🤔 
Thanks in advanced for sharing your insights! 🙏🏾

2021-04-06 09:07 UTC, tomaskallup commented
> One minor question from my side. I saw this PR in my notifications as I'm watching the project. And I must admit that I'm wondering where the borders of this plugin are intended to end. I'm a big fan of minimal plugins which do one thing and do it good. The plugin is called `gitsigns`. I think it makes sense and is nice that is also provide little extensions to interact with the hunks it highlights. For example do I consider the hunk reset quite helpful as it helps me while writing code. But interacting with a whole file sounds not like this is related anymore to signs or their according hunks. This goes more into the direction of what other git related plugins focus on. Those things I don't do writing but when I'm in the mode to stage changes, review my stuff and make a commit or so. So I start to wonder what is in the scope/target of this plugin here. Which features will be accepted and which will get declined? thinking
> Thanks in advanced for sharing your insights! 🙏🏾

I'd say this is still fine, as this doesn't really operate on whole file (except `reset_buffer_index`, but that would be hard to implement in another way). The `stage_buffer` just runs stage on all hunks in a file, so its just a mass version of `stage_hunk`. For this exact reason I created the issue first, to make sure it's desired.

2021-04-06 09:14 UTC, tomaskallup commented
A thing that comes in mind is maybe allowing to make "extensions", which in current state should be easy, as it's just a couple of `require`s for `gitsigns` libs. These could then implement extra actions & keybinds, but I feel like simple things like one function + a keybind isn't really bloat/non-minimal as you can just decide to not have the keybind and the function will never get called.

2021-04-06 09:27 UTC, lewis6991 commented
> One minor question from my side. I saw this PR in my notifications as I'm watching the project. And I must admit that I'm wondering where the borders of this plugin are intended to end. I'm a big fan of minimal plugins which do one thing and do it good. The plugin is called `gitsigns`. I think it makes sense and is nice that is also provide little extensions to interact with the hunks it highlights. For example do I consider the hunk reset quite helpful as it helps me while writing code. But interacting with a whole file sounds not like this is related anymore to signs or their according hunks. This goes more into the direction of what other git related plugins focus on. Those things I don't do writing but when I'm in the mode to stage changes, review my stuff and make a commit or so. So I start to wonder what is in the scope/target of this plugin here. Which features will be accepted and which will get declined? 🤔
> Thanks in advanced for sharing your insights! 🙏🏾

Picking the boundary is important. For me this plugin is essentially a git-lsp for the current buffer as the decorations and actions it provides only affect the current buffer.

Most of the code in this plugin is just an async framework for running git commands. Most of the functions are just leaf features that take advantage of this framework. So if you were to implement some other feature in a small plugin, you would need to replicate all the attach and async logic which probably makes up >50% of the codebase. For that reason I personally don't mind if the plugin steers more in the 'bloat' direction as long as:

- `require'gitsigns'.setup()` always does a sensible thing
- Most features are opt-in
- Core features are well tested. (A vast majority of small plugins, and even big ones don't have any form of testing).
- It's fast (this is really important)
 
For example the `current_line_blame` feature was actually very easy to implement and didn't require much additional code because all it does is call a version of `run_blame` on a `CursorHold` event and adds the output to virtual-text (via an extmark) instead of a preview window. There are other plugins that do this but do so without the well-tested framework gitsigns provides and also ends up requiring quite a lot of code.

> The plugin is called gitsigns. 

This is just the first name I could think of when initially implementing this. I don't really like the name, but I made it a point not to dwell on coming up with a really catchy an accurate name as a prerequisite to creating it. I just wanted to get my hands stuck in into some lua+async+git and produce something much better than existing plugins.

Also, the current feature set isn't much different to what `Signify` and `GitGutter` have. In fact I think `GitGutter` still has more features.

2021-04-06 09:35 UTC, lewis6991 requested changes

2021-04-06 09:35 UTC, lewis6991 commented on doc/gitsigns.txt
> +                and actual `git reset` on current file.
and -> an

2021-04-06 09:35 UTC, lewis6991 commented on teal/gitsigns.tl
> +  Status:clear()
`Status:clear()` -> `Status:clear_status()`

`clear_hunks` or `clear_diff` might be a better name.

2021-04-06 09:45 UTC, tomaskallup commented on doc/gitsigns.txt
> +                and actual `git reset` on current file.
Fixed

2021-04-06 09:47 UTC, lewis6991 requested changes

2021-04-06 09:47 UTC, lewis6991 commented on teal/gitsigns.tl
> +  Status:clear()
`Status:clear()` -> `Status:clear_diff()`

2021-04-06 09:49 UTC, lewis6991 approved these changes

2021-04-06 09:51 UTC, merged

2021-04-06 09:51 UTC, lewis6991 commented
Awesome! Thanks so much for this.

2021-04-06 10:55 UTC, weilbith commented
@lewis6991 thank you very much for your feedback! 😃