feat: Stage all hunks in a range.
lewis6991/gitsigns.nvim pull request #178
Opened 2021-05-06 01:36 UTC by sindrets

Fixes #176.

This seems to work. But I need to test it more thoroughly.

2021-05-06 11:01 UTC, lewis6991 requested changes
Can you also amend `doc/gitsigns.txt`?

2021-05-06 11:01 UTC, lewis6991 commented on teal/gitsigns.tl
> +local stage_hunk = async_void(function(_, range: {integer})
What's with the unused first argument?

2021-05-06 12:25 UTC, sindrets commented on teal/gitsigns.tl
> +local stage_hunk = async_void(function(_, range: {integer})
Indeed, it should be `{integer, integer}`. I have not written teal before, so I was just consulting docs and learning along the way. 

> What's with the unused first argument?

Good question. It has something to do with how plenary handles params for its async functions. And I didn't quite get to the bottom of it.

2021-05-06 12:25 UTC, sindrets commented on teal/gitsigns/hunks.tl
> +    end
I was gonna ask you that. I saw that you had this in the `find_hunk` function:

https://github.com/lewis6991/gitsigns.nvim/blob/06976b063a90c686a8b01234b8439ddcf2e7d1d6/teal/gitsigns/hunks.tl#L174-L176

So I assumed it was a special case.

2021-05-06 12:25 UTC, sindrets commented on teal/gitsigns/hunks.tl
> +    if (range[2] >= hunk.start and range[1] <= hunk.vend) then
Sure, I'll document it.

2021-05-06 12:28 UTC, lewis6991 commented on teal/gitsigns/hunks.tl
> +    end
Dam, wish I put a comment for that. It might be for when there is a single hunk that occupies the whole buffer. I think it's mainly used for untracked files which gitsigns adds signs for.

2021-06-09 23:35 UTC, sindrets commented
@lewis6991 sorry I left this for so long, got busy with other things. This seems to work quite well now. Both range staging and resetting works, as well as stage undo. I also added some visual mode mappings for `stage_hunk` and `reset_hunk`.

There was a bug in `create_patch` that I had to fix to get this to work correctly. When creating a patch for multiple hunks the block header generated by that function did not consider changes made by previous hunks. This was causing patches to be applied incorrectly when staging multiple hunks.

2021-06-09 23:42 UTC, sindrets commented on teal/gitsigns/hunks.tl
> +    process_hunk.removed.start = start + offset
This is necessary for `undo_stage_hunk` to work correctly after having staged multiple hunks in one patch.

2021-06-10 17:31 UTC, lewis6991 commented on doc/gitsigns.txt
> +                given range. If a range is provided, all hunks that intersect
`if {range} is provided`

2021-06-10 17:31 UTC, lewis6991 commented on doc/gitsigns.txt
> +                    {range} integer[]|nil Table of two integers making up the
Not sure how I feel about the `integer[]` notation. In teal this would be `{integer}` but I can see that would be confusing in this context.

For other fields I've just done  `table|nil` since the description is sufficient.

2021-06-10 17:31 UTC, lewis6991 commented on teal/gitsigns.tl
> +    'lua require("gitsigns")._run_func({<line1>, <line2>}, <f-args>)'
We're not using (and cannot use) `<line1>` and `<line2>` in the mappings so not sure I like its inclusion here since they will be passed to all functions which might not be desirable; `preview_hunk` for example.

Could he just make `stage_hunk` always work on a range if one is available so we can remove `-range` here and simplify the mappings? What do you think?

2021-06-10 17:31 UTC, lewis6991 commented on teal/gitsigns/actions.tl
> +end
Not sure this function is really adding anything. Can we inline it?

2021-06-10 17:31 UTC, lewis6991 commented on teal/gitsigns/hunks.tl
> +    process_hunk.removed.start = start + offset
Thanks for this. I've noticed a similar bug in my secondary signs PR.

2021-06-10 17:31 UTC, lewis6991 commented on teal/gitsigns/actions.tl
> +  for i = 1, #hunks do
Why not `for i, hunk in ipairs(hunks) do`?

2021-06-10 17:31 UTC, lewis6991 commented on teal/gitsigns/actions.tl
> +    range: {integer, integer} | nil)
Remove the `| nil`. All variables in teal have this implicitly. There have also been known issues in teal using this.

2021-06-10 17:31 UTC, lewis6991 commented on teal/gitsigns/hunks.tl
> +        table.insert(ret, hunk)
Can we change this to `ret[#ret+1] = hunk`? It's slightly more performant and I think it is a little bit easier to read.

2021-06-10 18:28 UTC, sindrets commented on teal/gitsigns.tl
> +    'lua require("gitsigns")._run_func({<line1>, <line2>}, <f-args>)'
Hm, I'm not sure. A range is not always going to be the visual range. I think we are ruining a lot of the flexibility by assuming users will only ever want to use this with a visual range. It would also make it a lot more difficult to add i.e. operator-pending mappings. 

But I agree that it's not very pretty to just slap on the range to the end of the args of all the action functions. Maybe we should instead store the range in a local variable in `actions.tl`, and then the action functions that expect a range can just check that variable?

I still think that `stage_hunk` and `reset_hunk` should have the range as part of their signature, so that you can call those methods with a range from lua.

On the topic of the messy looking signature for `reset_hunk`: I see that the current signature is 

```
function(bufnr: integer, hunk: Hunk)
```

But it is never called this way. So can we not just change it to:

```
function(range: {integer, integer})
```

2021-06-10 18:30 UTC, sindrets commented on teal/gitsigns/actions.tl
> +  for i = 1, #hunks do
Yeah, I'll change this. It was originally because I did some async awaits inside that loop, but I changed it later and forgot to fix the loop.

2021-06-10 19:44 UTC, sindrets commented on teal/gitsigns.tl
> +    'lua require("gitsigns")._run_func({<line1>, <line2>}, <f-args>)'
Okay, I implemented what I suggested: changing the signature of `reset_hunk` and storing user provided range in a var instead of appending it to the args of every action function. Please take a look at it and let me know what you think.

2021-06-11 11:28 UTC, lewis6991 commented on teal/gitsigns/actions.tl
> +  if range is {integer, integer} and range[1] ~= range[2] then
Do we need the first term anymore?

2021-06-11 11:28 UTC, lewis6991 commented on teal/gitsigns/config.tl
> +      ['v <leader>hs'] = '<cmd>lua require"gitsigns".stage_hunk({vim.fn.line("."), vim.fn.line("v")})<CR>',
I've considered changing the default mappings to use the corresponding Gitsigns commands instead. Now we've introduced ranges maybe that decision is more justified? Not to be done in this PR but what do you think?

2021-06-11 11:29 UTC, lewis6991 commented on teal/gitsigns/actions.tl
> +  if range is {integer, integer} and range[1] ~= range[2] then
Actually, I guess we do for the nil check.

2021-06-11 11:30 UTC, lewis6991 approved these changes

2021-06-11 12:47 UTC, sindrets commented on teal/gitsigns/config.tl
> +      ['v <leader>hs'] = '<cmd>lua require"gitsigns".stage_hunk({vim.fn.line("."), vim.fn.line("v")})<CR>',
That would certainly make the mappings a lot more compact. I think it's a good idea.

2021-06-15 13:16 UTC, sindrets commented
@lewis6991 Can we merge this, or is it blocked by something?

2021-06-15 13:17 UTC, lewis6991 commented
The change has a merge conflict that needs resolving. Rebase on `main` then we can merge.

2021-06-15 13:17 UTC, lewis6991 commented
Also squash your commits.

2021-06-15 14:36 UTC, sindrets commented
> The change has a merge conflict that needs resolving.

Strange. Github showed no conflicts on my end. But I have rebased now.

> Also squash your commits.

You can choose to squash when you merge. Should be available from the dropdown on the merge button unless you have explicitly disabled it for this repo.

2021-06-15 14:48 UTC, lewis6991 commented
Many thanks.

2021-06-15 14:48 UTC, merged

2021-06-15 14:50 UTC, lewis6991 commented
> You can choose to squash when you merge. Should be available from the dropdown on the merge button unless you have explicitly disabled it for this repo.

You can choose to "squash and merge" or "rebase and merge". I want both so I have "rebase and merge" set as default. Basically I just want to avoid introducing merge commits into the history.

2021-06-15 15:22 UTC, sindrets commented
Ah, so "squash and merge" may introduce additional merge commits? Didn't know that, thanks.

2021-06-15 15:24 UTC, lewis6991 commented
Well, I don't know if it does tbh, but since there is no rebase I'd imagine it would.