wip: current line blame relative string
lewis6991/gitsigns.nvim pull request #236
Opened 2021-06-28 20:14 UTC by zapling

Closes #186

2021-06-29 20:06 UTC, zapling commented
@lewis6991 any initial thoughts on this?

2021-06-29 20:15 UTC, lewis6991 commented
Generally looks good, have a few points but on vacation this week so won't have non-mobile access until Monday.

2021-07-04 13:19 UTC, lewis6991 requested changes
`gitsigns.util` seems like a sensible place to put this, however it will unecessarily increase the require time of util and since it is used by `setup` and `attach` it will make startup a tiny bit slower, even if the user doesn't use relative date. Not really a problem for now, but I may move everything in `util.tl` to something like `util_private.tl` so util is only loaded by users that want it.

2021-07-04 13:19 UTC, lewis6991 commented on teal/gitsigns/config.tl
> +          date_time = require('gitsigns.util').get_relative_time(tonumber(blame_info['author_time']))
I would just put this in a comment and remove the `if false`

2021-07-04 13:19 UTC, lewis6991 commented on teal/gitsigns/util.tl
> +  current_timestamp = os.time()
Combine these lines: `local current_timestamp = os.time()`, `number` should be inferred.

2021-07-04 13:19 UTC, lewis6991 commented on teal/gitsigns/util.tl
> +function M.get_relative_time(timestamp: number): string
Timestamp is really an `integer` (not a number), but I guess it doesn't matter too much.

2021-07-04 13:19 UTC, lewis6991 commented on teal/gitsigns/util.tl
> +  local elasped = current_timestamp - timestamp
`elasped` -> `elapsed`

2021-07-04 13:19 UTC, lewis6991 commented on teal/gitsigns/util.tl
> +  if elasped == 0 then
Move above L62.

2021-07-04 13:19 UTC, lewis6991 commented on teal/gitsigns/util.tl
> +    number = math.floor(time / divisor)
Combine and don't use `number` as an ident as it is a keyword: 
```lua
local num = math.floor(time/divisor)
```

2021-07-04 13:19 UTC, lewis6991 commented on teal/gitsigns/util.tl
> +    return to_relative_string(elasped, 60, 'minute')
Shouldn't `60` be `minute_seconds`?

2021-07-04 13:19 UTC, lewis6991 commented on teal/gitsigns/config.tl
> +        local date_time: string
It might be worth adding a opts field to the formatter function with a field `relative_date`. We can then add something like `current_line_blame_opts` into the config so 80% of users won't need to define a custom formatter function for this?

2021-07-04 13:48 UTC, zapling commented on teal/gitsigns/util.tl
> +function M.get_relative_time(timestamp: number): string
I guess `tonumber()` parses the string to a number when we convert `blame_info['author_time']` because that was giving me issues if I changed the param type to `integer`

2021-07-04 13:48 UTC, zapling commented on teal/gitsigns/config.tl
> +        local date_time: string
Yes, this sounds way better than having to redefine the function.

2021-07-04 13:49 UTC, lewis6991 commented on teal/gitsigns/util.tl
> +function M.get_relative_time(timestamp: number): string
Yeah, you would need to cast to an integer with `as integer`. Like I said, not a big deal.

2021-07-04 14:42 UTC, zapling commented on teal/gitsigns/config.tl
> +    ]]
What would be a good example format for these options here? @lewis6991

2021-07-04 14:42 UTC, zapling commented on teal/gitsigns/config.tl
> +    end
My thinking was that maybe we move the other separate options we have for `current_line_blame` into here as well, but maybe in another PR, as that would be a breaking change?

2021-07-04 14:49 UTC, lewis6991 commented on teal/gitsigns/config.tl
> +    ]]
I think this looks fine. I'd remove the reference to `gitsigns`.

Also we should probably name this `current_line_blame_formatter_opts` as I'm not sure the other options belong in here.

2021-07-04 14:50 UTC, lewis6991 commented on teal/gitsigns/config.tl
> +    end
Maybe, the options here are explicitly for the formatter so we may not need to move them.

2021-07-05 15:45 UTC, zapling commented on teal/gitsigns/config.tl
> +    end
right, makes sense

2021-07-05 15:48 UTC, lewis6991 commented on teal/gitsigns/config.tl
> +        date_time = os.date('%Y-%m-%d', tonumber(blame_info['author_time']))
Put this in an else branch below.

2021-07-05 15:48 UTC, lewis6991 commented on teal/gitsigns/config.tl
> +        end
Update this.

2021-07-05 16:10 UTC, zapling commented
I'm slightly confused on how I would squash my commits, as I did fix a merge conflict pulling in `main` inbetween, did I fuck up haha :sweat_smile:

2021-07-05 16:44 UTC, lewis6991 commented
You did a merge as opposed to a rebase. Easiest thing to do would be to do a soft reset to main and reapply the changes as a single commit.

2021-07-05 17:02 UTC, lewis6991 approved these changes

2021-07-05 17:03 UTC, lewis6991 commented
That was trickier than I thought it be. I ended up just doing `git rebase main` and fixing each conflict.

2021-07-05 17:05 UTC, merged