Add persistent diff base setup option
lewis6991/gitsigns.nvim pull request #349
Opened 2021-09-04 02:25 UTC by Saecki

Implements #309

2021-09-04 12:00 UTC, lewis6991 requested changes

2021-09-04 12:00 UTC, lewis6991 commented on teal/gitsigns/actions.tl
> +  config.diff_base = base
Not sure we should do this. Change_base() is only designed to work on the current buffer. We could maybe add a global option which changes the base of all buffers and changes config.

2021-09-04 13:12 UTC, Saecki commented on teal/gitsigns/actions.tl
> +  config.diff_base = base
Makes sense. Do you mean a global `parameter` or another function? If you mean function, maybe rename it `buf_change_base` and name the global one `change_base` that would make it more obvious for me?

2021-09-04 13:25 UTC, Saecki commented on teal/gitsigns/actions.tl
> +  config.diff_base = base
Otherwise what do you think of something like this:
```lua
M.change_base = function(base: string, global: boolean)
  base = calc_base(base)

  if global then
    config.diff_base = base
    
    for buf,bcache in pairs(cache as {integer:CacheEntry}) do
      bcache.base = base
      bcache.compare_text = nil
      void(manager.update)(buf, bcache)
    end
  else
    local buf = current_buf()
    local bcache = cache[buf]
    if not bcache then return end

    bcache.base = base
    bcache.compare_text = nil
    void(manager.update)(buf, bcache)
  end
end
```

2021-09-05 14:50 UTC, lewis6991 commented on teal/gitsigns/actions.tl
> +  config.diff_base = base
That's exactly what I had in mind. :+1:

2021-09-05 23:57 UTC, Saecki commented
To update multiple buffers that are open in splits, I had to change the `manager.update` function. I hope that isn't too hacky.

2021-09-06 10:27 UTC, lewis6991 commented
I surprised you needed to do that. The change looks more like an optimization, as it allows different buffers to be updated at the same time, instead of sequentially, but either way I would expect the end result to be the same. If it's needed, then there's likely a bug lurking somewhere.

2021-09-06 10:29 UTC, lewis6991 commented on doc/gitsigns.txt
> +                just the current one.
... of all buffers including any new buffers.

Remove "not just the current one".

2021-09-06 10:30 UTC, lewis6991 commented on doc/gitsigns.txt
> +      The object/revision hash to diff against.
Remove hash since a revision may not be a hash.

2021-09-06 10:32 UTC, lewis6991 commented on teal/gitsigns/actions.tl
> +    void(manager.update)(buf, bcache)
I would make change_base async and call the updates asynchronously.

I.e. wrap `change_base` in `void`, and call the version of update which is not wrapped in void.

This will cause all updates to happen sequentially.

2021-09-06 20:02 UTC, Saecki commented on doc/gitsigns.txt
> +      The object/revision hash to diff against.
Oops, forgot to run `make gen_help`.

2021-09-06 20:21 UTC, Saecki commented on teal/gitsigns/actions.tl
> +    void(manager.update)(buf, bcache)
Was [that](https://github.com/lewis6991/gitsigns.nvim/pull/349/commits/22682e1329ef783c64dfdb2d60a4ab40798d3932) it, or do you mean the `update` function inside `manager`?

2021-09-06 20:25 UTC, lewis6991 commented on teal/gitsigns/actions.tl
> +    void(manager.update)(buf, bcache)
LGTM. Does it work properly without your change to manager.tl?

2021-09-06 20:28 UTC, Saecki commented on teal/gitsigns/actions.tl
> +    void(manager.update)(buf, bcache)
Yes, works fine

2021-09-06 21:11 UTC, lewis6991 commented on teal/gitsigns/actions.tl
> +    void(manager.update)(buf, bcache)
Ok. Can revert the manager.tl change for this PR? The change is ok but would prefer it is done separately just in case we need to revert it.

2021-09-07 15:24 UTC, Saecki commented on teal/gitsigns/actions.tl
> +    void(manager.update)(buf, bcache)
Done

2021-09-07 15:35 UTC, lewis6991 commented on teal/gitsigns/config.tl
> +    default_help = "object/revision to diff against",
default_help is just a way of overriding how the default value is rendered.

In this case, the default base is the index.

2021-09-07 15:36 UTC, Saecki commented on teal/gitsigns/config.tl
> +    default_help = "object/revision to diff against",
Ahh ok

2021-09-07 16:43 UTC, Saecki commented
So I realized that when running the `Gitsigns change_base` with the global option there is no way to select the default by omitting the argument. And as far as I can tell there is no way to specify a git object/revision for the index (Is there?).
Should we recognize `*` or  the string `nil` and set the `diff_base` to nil? So one could run `Gitsigns change_base * true` to change the base of all buffers to the default one.

2021-09-07 16:51 UTC, lewis6991 commented
Doesn't `:Gitsigns nil true` work?

2021-09-07 16:53 UTC, Saecki commented
When calling the lua function yes, when calling the vim command no. It is parsed as a string and then passed to git as an object/revision.

2021-09-09 14:58 UTC, lewis6991 commented
For now I've just added `reset_base({global})` to get around this.

2021-09-09 15:05 UTC, merged