Optionally loop around file when navigation hunks.
lewis6991/gitsigns.nvim pull request #38
Opened 2020-12-22 17:26 UTC by aliou

Hello!

First off, thank you very much for gitsigns, I didn't realise how slow other solutions were before trying this.

This pull requests allows passing optional options to `next_hunk` and `prev_hunk` to disable wrapping around the file without having to touch the `wrapscan` global option. I used the LSP's [`goto_next` and `goto_prev`](](https://github.com/neovim/neovim/blob/b931a554d70ef07803da3eb3f98ce4b3a3570d11/runtime/lua/vim/lsp/diagnostic.lua#L568-L592)) as inspiration for how the API should look like but I can change to only pass a boolean to the function if you prefer.

Thanks!

2020-12-22 21:18 UTC, lewis6991 commented on doc/gitsigns.txt
> +                            • {wrap}: (boolean, default true)
Strictly speaking it doesn't default to true. Maybe worth omitting since you mention the default below?

2020-12-22 21:19 UTC, lewis6991 commented on doc/gitsigns.txt
> +                              • Whether to loop around file or not. Defaults
I think the bullet can be removed (not the text, just the dot).

2020-12-22 21:25 UTC, lewis6991 requested changes
Thanks for this. Just some minor things on the docs.

2020-12-23 08:43 UTC, aliou commented
Thanks for the review, I updated the code following your comments!

2020-12-23 09:14 UTC, lewis6991 approved these changes

2020-12-23 09:15 UTC, merged

2020-12-27 10:42 UTC, aliou commented
Thanks!