Fix diff on windows. #61
lewis6991/gitsigns.nvim pull request #64
Opened 2021-02-25 19:22 UTC by Acelya-9028

Sorry for the delay.

`await_main()` prevents `os.tmpname ()` from crashing.
`--ignore-space-at-eol` prevents diff to be the whole file when `bcache.staged` use `\r\n` instead of `\n`.

2021-02-25 19:35 UTC, lewis6991 commented
Thanks for this. You just need to run `make tl-build` to update the lua files.

2021-02-25 19:37 UTC, lewis6991 requested changes

2021-02-25 19:37 UTC, lewis6991 commented on teal/gitsigns.tl
> +  await_main()
Can you add a comment saying this is explicitly needed for Windows:

```
On windows os.tmpname() crashes in callback threads.
```

2021-02-25 19:37 UTC, lewis6991 commented on teal/gitsigns/git.tl
> +        '--ignore-space-at-eol',
Again a comment why this is needed would be appreciated.

2021-02-26 17:17 UTC, Acelya-9028 commented
Ok after many hours of fighting to install luarocks and teal, it's a fail sniff xD

```powershell
→ ~\AppData\Local\nvim-data\site\pack\paqs\start\gitsigns.nvim [main ↑2]› tl --version
0.11.2
```

2021-02-26 18:14 UTC, lewis6991 commented
Checks are still failing. Probably a Windows issue. Don't worry, I'll make the changes.

2021-02-26 18:16 UTC, Acelya-9028 commented
Ok when trying to fix the line ending problem, I found that `git config --global core.autocrlf input` makes neovim crash at startup.

`git config --global core.autocrlf true` or `git config --global core.autocrlf true` works well.

The crash appear in `git.run_diff`, I investigate.

2021-02-27 10:48 UTC, closed without merging

2021-02-27 10:48 UTC, lewis6991 commented
Changes applied in https://github.com/lewis6991/gitsigns.nvim/pull/66